Add debug info
Summary:
Errors: https://github.com/facebook/capi-param-builder/actions/runs/18319749778/job/52169532685
on authentication fail
Add debug info

Differential Revision:
D84071921

Privacy Context Container: L1384019

fbshipit-source-id: 7f4a4e7d811506c100b80bce127c1ca7d9201e22

diff --git a/.github/workflows/ruby_cd.yml b/.github/workflows/ruby_cd.yml
--- a/.github/workflows/ruby_cd.yml
+++ b/.github/workflows/ruby_cd.yml
@@ -22,10 +22,22 @@ jobs:
       - name: Gem deploy
         run: |
           mkdir -p ~/.gem
-          touch ~/.gem/credentials
+          echo -e "---\n:rubygems_api_key: $RUBYGEMS_API_KEY\n" > ~/.gem/credentials
           chmod 0600 ~/.gem/credentials
-          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > ~/.gem/credentials
-          gem build *.gemspec
-          gem push *.gem
         env:
           RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
+      - name: debug info
+        run: |
+          if [ ! -f ~/.gem/credentials ]; then
+            echo "Credentials file not found!"
+          exit 1
+          fi
+          if ! grep -q ":rubygems_api_key:" ~/.gem/credentials; then
+            echo "API key not found in credentials file!"
+            exit 1
+          fi
+          echo "Credentials file looks good."
+      - name: Build gem
+        run: gem build *.gemspec
+      - name: Publish gem to RubyGems
+        run: gem push *.gem
